
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author arauj
 */
public class AlterarDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form AlterarDepartamento
     */
    public AlterarDepartamento() {
        initComponents();
    }

    public AlterarDepartamento(String id, String nome, String telefone) {
        initComponents();

        txtCodDepartamento.setText(id);
        txtCodDepartamento.setEnabled(false);
        cmbNomeDapartamento.setSelectedItem(nome);
        txtTelefoneDepartamento.setText(telefone);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodDepartamento = new javax.swing.JLabel();
        lblNomeDepartamento = new javax.swing.JLabel();
        txtCodDepartamento = new javax.swing.JTextField();
        lblTelefoneDepartamento = new javax.swing.JLabel();
        txtTelefoneDepartamento = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        cmbNomeDapartamento = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Departamento");
        getContentPane().setLayout(null);

        lblCodDepartamento.setText("Código do Departamento");
        getContentPane().add(lblCodDepartamento);
        lblCodDepartamento.setBounds(10, 40, 160, 40);

        lblNomeDepartamento.setText("Nome do Departmento");
        getContentPane().add(lblNomeDepartamento);
        lblNomeDepartamento.setBounds(10, 110, 150, 40);
        getContentPane().add(txtCodDepartamento);
        txtCodDepartamento.setBounds(190, 40, 210, 40);

        lblTelefoneDepartamento.setText("Telefone do Departamento");
        getContentPane().add(lblTelefoneDepartamento);
        lblTelefoneDepartamento.setBounds(10, 180, 150, 40);
        getContentPane().add(txtTelefoneDepartamento);
        txtTelefoneDepartamento.setBounds(190, 180, 220, 40);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(170, 300, 210, 40);

        cmbNomeDapartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Departamento de Recursos Humanos (RH)", "Departamento Financeiro", "Departamento de Marketing", "Departamento de Vendas", "Departamento de Operações", "Departamento de TI", "Departament de Compras", "Departamento de Logística", "Departamento Jurídico", "Departamento de Pesquisa e Desenvolvimento" }));
        getContentPane().add(cmbNomeDapartamento);
        cmbNomeDapartamento.setBounds(190, 110, 320, 40);

        setSize(new java.awt.Dimension(567, 398));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //1 - Pegar os dados digitados nos campos e guardar em variáveis
        String codDepart, nomeDepart, telefoneDepart;

        codDepart = txtCodDepartamento.getText();
        nomeDepart = cmbNomeDapartamento.getSelectedItem().toString();
        telefoneDepart = txtTelefoneDepartamento.getText();

        try {
            //2 - Conectar ao Banco de Dados empresa
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa", "root", "");

            //3 - Enviar os dados para a tabela do BD
            PreparedStatement st = conectar.prepareStatement("UPDATE departamento SET nome = ?, telefone = ? WHERE nome = ?");
            st.setString(1, nomeDepart);
            st.setString(2, telefoneDepart);
            st.setString(3, nomeDepart);
            st.executeUpdate(); // Executa o comando INSERT

            //4 - Exibir um mensagem para o usuário
            JOptionPane.showMessageDialog(null, "Departamento alterado com sucesso");
            dispose();
            
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());

        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbNomeDapartamento;
    private javax.swing.JLabel lblCodDepartamento;
    private javax.swing.JLabel lblNomeDepartamento;
    private javax.swing.JLabel lblTelefoneDepartamento;
    private javax.swing.JTextField txtCodDepartamento;
    private javax.swing.JTextField txtTelefoneDepartamento;
    // End of variables declaration//GEN-END:variables
}
