
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author fabricio.asantana1
 */
public class ListarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form ListarUsuarios
     */
    public ListarUsuarios() {
        initComponents();
        listarUsuarios();
    }

    private void listarUsuarios() {
        try {
            //1 - Conectar ao banco de dados;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa", "root", "");

            //2 - Buscar todos os dados que eu quero exibir na tabela;
            PreparedStatement st = conectar.prepareStatement("SELECT * FROM usuarios");
            ResultSet usuarios = st.executeQuery(); // Executa o SELECT acima

            // Criando um modelo da tabela no listarUsuarios para adiciona as informações da tabela usuarios;
            DefaultTableModel tblModelo = (DefaultTableModel) tblUsuario.getModel();
            tblModelo.setRowCount(0); // Limpa a tabela

            // Faça linha por linha até o final da tabela;  
            while (usuarios.next()) {
                String[] linha = {
                    usuarios.getString("usuario"),
                    usuarios.getString("senha"),
                    usuarios.getString("cargo")
                };
                tblModelo.addRow(linha);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        lblCargo = new javax.swing.JLabel();
        cmbCargo = new javax.swing.JComboBox<>();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listagem de Usuários");
        getContentPane().setLayout(null);

        tblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblUsuario.setForeground(new java.awt.Color(0, 0, 255));
        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuário", "Senha", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsuario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 110, 680, 320);

        lblCargo.setText("Cargo:");
        getContentPane().add(lblCargo);
        lblCargo.setBounds(40, 30, 50, 30);

        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Administrador", "Gerente", "Estagiário", "Vendedor" }));
        cmbCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCargoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCargo);
        cmbCargo.setBounds(90, 30, 130, 30);

        lblUsuario.setText("Usuário:");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(250, 30, 70, 30);

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(310, 30, 280, 30);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(640, 30, 75, 30);

        setSize(new java.awt.Dimension(781, 494));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCargoActionPerformed
        //0 - Obter o cargo para a filtragem;
        String cargo;
        cargo = cmbCargo.getSelectedItem().toString();
        
        if(cargo == "Todos"){
            listarUsuarios();
            return; // Para a execução  - stop
        }
            
        try {
            //1 - Conectar ao banco de dados;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa", "root", "");

            //2 - Buscar todos os dados que eu quero exibir na tabela;
            PreparedStatement st = conectar.prepareStatement("SELECT * FROM usuarios WHERE cargo=?");
            st.setString(1, cargo);
            ResultSet usuarios = st.executeQuery(); // Executa o SELECT acima

            // Criando um modelo da tabela no listarUsuarios para adiciona as informações da tabela usuarios;
            DefaultTableModel tblModelo = (DefaultTableModel) tblUsuario.getModel();
            tblModelo.setRowCount(0); // Limpa a tabela
 
            // Faça linha por linha até o final da tabela;  
            while (usuarios.next()) {
                String[] linha = {
                    usuarios.getString("usuario"),
                    usuarios.getString("senha"),
                    usuarios.getString("cargo")
                };
                tblModelo.addRow(linha);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());

        }
    }//GEN-LAST:event_cmbCargoActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        //0 - Obter o cargo para a filtragem;
        String u;
        u = txtUsuario.getText();
                
        try {
            //1 - Conectar ao banco de dados;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa", "root", "");

            
            //2 - Buscar todos os dados que eu quero exibir na tabela;
           PreparedStatement st = conectar.prepareStatement("SELECT * FROM usuarios WHERE usuario LIKE ?");
            st.setString(1, "%" + u + "%");
            ResultSet usuarios = st.executeQuery(); // Executa o SELECT acima

            // Criando um modelo da tabela no listarUsuarios para adiciona as informações da tabela usuarios;
            DefaultTableModel tblModelo = (DefaultTableModel) tblUsuario.getModel();
            tblModelo.setRowCount(0); // Limpa a tabela
 
            // Faça linha por linha até o final da tabela;  
            while (usuarios.next()) {
                String[] linha = {
                    usuarios.getString("usuario"),
                    usuarios.getString("senha"),
                    usuarios.getString("cargo")
                };
                tblModelo.addRow(linha);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());

        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
