
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.print.attribute.standard.Finishings;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author fabricio.asantana1
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    //Construtor padrão;
    public Menu() {
        initComponents();
    }

    // Construtor para o cargo do usuário;
    public Menu(String cargo) {
        initComponents();

        if (cargo.equalsIgnoreCase("Administrador")) {

        } else if (cargo.equalsIgnoreCase("Gerente")) {
            mnuUsuarios.setVisible(false);

        } else if (cargo.equalsIgnoreCase("Estagiário")) {
            mnuFuncionarios.setVisible(false);
            mnuUsuarios.setVisible(false);
            itmCadastrarDepartamentos.setEnabled(false);
            itmAlterarDepartamentos.setEnabled(false);
            itmExcluirDepartamentos.setEnabled(false);

        } else if (cargo.equalsIgnoreCase("Vendedor")) {
            mnuDepartamentos.setVisible(false);
            mnuUsuarios.setVisible(false);
            itmCadastrarFuncionario.setEnabled(false);
            itmAlterarFuncionarios.setEnabled(false);
            itmExcluirFuncionario.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuDepartamentos = new javax.swing.JMenu();
        itmCadastrarDepartamentos = new javax.swing.JMenuItem();
        itmExcluirDepartamentos = new javax.swing.JMenuItem();
        itmAlterarDepartamentos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itmListarDepartamentos = new javax.swing.JMenuItem();
        itmBuscarDepartamentos = new javax.swing.JMenuItem();
        mnuFuncionarios = new javax.swing.JMenu();
        itmCadastrarFuncionario = new javax.swing.JMenuItem();
        itmExcluirFuncionario = new javax.swing.JMenuItem();
        itmAlterarFuncionarios = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itmListarFuncionario = new javax.swing.JMenuItem();
        itmBuscarFuncionarios = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        itmCadastraUsuarios = new javax.swing.JMenuItem();
        itmExcluirUsuarios = new javax.swing.JMenuItem();
        itmAlterarUsuarios = new javax.swing.JCheckBoxMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itmListarUsuarios = new javax.swing.JMenuItem();
        itmBuscarUsuarios = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        itmSobre = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal do Sistema");
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-40, -70, 990, 640);

        mnuDepartamentos.setMnemonic('D');
        mnuDepartamentos.setText("Departamentos");

        itmCadastrarDepartamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCadastrarDepartamentos.setText("Cadastrar");
        itmCadastrarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarDepartamentosActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmCadastrarDepartamentos);

        itmExcluirDepartamentos.setText("Excluir");
        itmExcluirDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirDepartamentosActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmExcluirDepartamentos);

        itmAlterarDepartamentos.setText("Alterar");
        itmAlterarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarDepartamentosActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmAlterarDepartamentos);
        mnuDepartamentos.add(jSeparator1);

        itmListarDepartamentos.setText("Listar");
        itmListarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarDepartamentosActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmListarDepartamentos);

        itmBuscarDepartamentos.setText("Buscar");
        itmBuscarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarDepartamentosActionPerformed(evt);
            }
        });
        mnuDepartamentos.add(itmBuscarDepartamentos);

        jMenuBar1.add(mnuDepartamentos);

        mnuFuncionarios.setMnemonic('F');
        mnuFuncionarios.setText("Funcionários");

        itmCadastrarFuncionario.setText("Cadastrar");
        itmCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarFuncionarioActionPerformed(evt);
            }
        });
        mnuFuncionarios.add(itmCadastrarFuncionario);

        itmExcluirFuncionario.setText("Excluir");
        itmExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirFuncionarioActionPerformed(evt);
            }
        });
        mnuFuncionarios.add(itmExcluirFuncionario);

        itmAlterarFuncionarios.setText("Alterar");
        itmAlterarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarFuncionariosActionPerformed(evt);
            }
        });
        mnuFuncionarios.add(itmAlterarFuncionarios);
        mnuFuncionarios.add(jSeparator3);

        itmListarFuncionario.setText("Listar");
        itmListarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarFuncionarioActionPerformed(evt);
            }
        });
        mnuFuncionarios.add(itmListarFuncionario);

        itmBuscarFuncionarios.setText("Buscar");
        itmBuscarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarFuncionariosActionPerformed(evt);
            }
        });
        mnuFuncionarios.add(itmBuscarFuncionarios);

        jMenuBar1.add(mnuFuncionarios);

        mnuUsuarios.setMnemonic('U');
        mnuUsuarios.setText("Usuários");

        itmCadastraUsuarios.setText("Cadastrar");
        itmCadastraUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastraUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(itmCadastraUsuarios);

        itmExcluirUsuarios.setText("Excluir");
        itmExcluirUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(itmExcluirUsuarios);

        itmAlterarUsuarios.setText("Alterar");
        itmAlterarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(itmAlterarUsuarios);
        mnuUsuarios.add(jSeparator2);

        itmListarUsuarios.setText("Listar");
        itmListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(itmListarUsuarios);

        itmBuscarUsuarios.setText("Buscar");
        itmBuscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(itmBuscarUsuarios);

        jMenuBar1.add(mnuUsuarios);

        mnuAjuda.setMnemonic('J');
        mnuAjuda.setText("Ajuda");

        jMenuItem1.setText("Instruções de uso");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuAjuda.add(jMenuItem1);

        itmSobre.setText("Sobre");
        mnuAjuda.add(itmSobre);

        jMenuBar1.add(mnuAjuda);

        mnuSair.setMnemonic('S');
        mnuSair.setText("Sair");
        mnuSair.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnuSairItemStateChanged(evt);
            }
        });
        mnuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSairMouseClicked(evt);
            }
        });
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(911, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmCadastrarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarDepartamentosActionPerformed
        new CadastrarDepartamentos().setVisible(true);
    }//GEN-LAST:event_itmCadastrarDepartamentosActionPerformed

    private void itmExcluirDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirDepartamentosActionPerformed
        //Pedindo o usuário à excluir
        String i;

        i = JOptionPane.showInputDialog(null, "Excluir:", "Excluir Departamentos", JOptionPane.INFORMATION_MESSAGE);
        try {
            //Conectar ao BD
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa", "root", "");

            //Excluir o usuário informado
            PreparedStatement st = conectar.prepareStatement("DELETE FROM departamento WHERE id= ?");
            st.setString(1, i);
            int retorno = st.executeUpdate(); //Executa o DELETE 

            if (retorno == 1) { //Exibir uma mensagem para o usuário
                JOptionPane.showMessageDialog(null, "Departamento excluído com sucesso");

            } else { // Exibir uma mensagem de erro para o usuário
                JOptionPane.showMessageDialog(null, "Departamento não encontrado", "Mensagem", HEIGHT);
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmExcluirDepartamentosActionPerformed

    private void itmCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarFuncionarioActionPerformed
        new CadastrarFuncionario().setVisible(true);
    }//GEN-LAST:event_itmCadastrarFuncionarioActionPerformed

    private void itmAlterarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarFuncionariosActionPerformed
        String nomeFuncionario;

        nomeFuncionario = JOptionPane.showInputDialog(null, "Nome do funcionário a alterar", "Alterar Funcionário", JOptionPane.INFORMATION_MESSAGE);

        try {
            //1 - Conectar ao BD;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa", "root", "");

            //2 - Preparar o comando SQL;
            PreparedStatement st = conectar.prepareStatement("SELECT * FROM funcionarios WHERE nome = ?");
            st.setString(1, nomeFuncionario);
            ResultSet funcionario = st.executeQuery();

            if (funcionario.next()) {
                String nome, cargo, data, hora;

                nome = funcionario.getString("nome");
                cargo = funcionario.getString("cargo");
                data = funcionario.getString("data");
                hora = funcionario.getString("hora");

                new AlterarFuncionario(nome, cargo, data, hora).setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Funcionário não encontrado");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_itmAlterarFuncionariosActionPerformed

    private void itmListarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarFuncionarioActionPerformed
        new ListarFuncionarios().setVisible(true);
    }//GEN-LAST:event_itmListarFuncionarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itmCadastraUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastraUsuariosActionPerformed
        new CadastrarUsuarios().setVisible(true);
    }//GEN-LAST:event_itmCadastraUsuariosActionPerformed

    private void itmExcluirUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirUsuariosActionPerformed
        //Pedindo o usuário à excluir
        String u;

        u = JOptionPane.showInputDialog(null, "Excluir:", "Excluir usuários", JOptionPane.INFORMATION_MESSAGE);
        try {
            //Conectar ao BD
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa", "root", "");

            //Excluir o usuário informado
            PreparedStatement st = conectar.prepareStatement("DELETE FROM usuarios WHERE usuario = ?");
            st.setString(1, u);
            int retorno = st.executeUpdate(); //Executa o DELETE 

            if (retorno == 1) { //Exibir uma mensagem para o usuário
                JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso");

            } else { // Exibir uma mensagem de erro para o usuário
                JOptionPane.showMessageDialog(null, "Usuário não encontrado", "Mensagem", HEIGHT);
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_itmExcluirUsuariosActionPerformed

    private void itmAlterarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarUsuariosActionPerformed
        //1- Obter o nome do usuário a alterar;
        String u;

        u = JOptionPane.showInputDialog(null, "Usuário a alterar");

        try {
            //2- Conectar ao BD
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa", "root", "");

            //3 - Buscar esse usuário na tabela do BD;
            PreparedStatement st = conectar.prepareStatement("SELECT * FROM usuarios WHERE usuario=?");
            st.setString(1, u);
            ResultSet usuario = st.executeQuery(); // executa o SELECT

            //4- Verificar se encontrou o usuário na tabela do BD;
            if (usuario.next()) { //Se encontrou o usuário
                //5 - Enviar os dados do usuario para a tela AlteararUsuarios
                String usu, sen, car;

                usu = usuario.getString("usuario");
                sen = usuario.getString("senha");
                car = usuario.getString("cargo");

                new AlterarUsuarios(usu, sen, car).setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Usuário não encontado!");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_itmAlterarUsuariosActionPerformed

    private void itmListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarUsuariosActionPerformed
        new ListarUsuarios().setVisible(true);
    }//GEN-LAST:event_itmListarUsuariosActionPerformed

    private void mnuSairItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnuSairItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSairItemStateChanged

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed

    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mnuSairMouseClicked

    private void itmBuscarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarFuncionariosActionPerformed
        String nomeFuncionario;

        nomeFuncionario = JOptionPane.showInputDialog(null, "Buscar Funcionário");

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa", "root", "");

            PreparedStatement st = conectar.prepareStatement("SELECT * FROM funcionarios WHERE nome = ?");
            st.setString(1, nomeFuncionario);
            ResultSet funcionario = st.executeQuery();

            if (funcionario.next()) {
                String nome, cargo, data, hora;

                nome = funcionario.getString("nome");
                cargo = funcionario.getString("cargo");
                data = funcionario.getString("data");
                hora = funcionario.getString("hora");

                JOptionPane.showMessageDialog(null,
                        "Nome do Funcionário: " + nome + "\n"
                        + "Cargo do Funcionário: " + cargo + "\n"
                        + "Data de Entrada: " + data + "\n"
                        + "Hora de trabalho semanalmente: " + hora
                );

            } else {
                JOptionPane.showMessageDialog(null, "Funcionário não encontrado");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }


    }//GEN-LAST:event_itmBuscarFuncionariosActionPerformed

    private void itmBuscarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarUsuariosActionPerformed
        //1- Obter o nome do usuário a alterar;
        String u;

        u = JOptionPane.showInputDialog(null, "Buscar Usuário");

        try {
            //2- Conectar ao BD
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa", "root", "");

            //3 - Buscar esse usuário na tabela do BD;
            PreparedStatement st = conectar.prepareStatement("SELECT * FROM usuarios WHERE usuario=?");
            st.setString(1, u);
            ResultSet usuario = st.executeQuery(); // executa o SELECT

            //4- Verificar se encontrou o usuário na tabela do BD;
            if (usuario.next()) { //Se encontrou o usuário
                //5 - Enviar os dados do usuario para a tela AlteararUsuarios
                String usu, sen, car;

                usu = usuario.getString("usuario");
                sen = usuario.getString("senha");
                car = usuario.getString("cargo");

                JOptionPane.showMessageDialog(null, "Nome do usuário:" + usu + "\n" + "Senha:" + sen + "\n" + "Cargo:" + car, "Mostrar Usuário", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Usuário não encontado!");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }


    }//GEN-LAST:event_itmBuscarUsuariosActionPerformed

    private void itmExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirFuncionarioActionPerformed
        String nomeFuncionario;

        nomeFuncionario = JOptionPane.showInputDialog(null, "Digite o nome do funcionário para excluir", "Excluir funcionário", JOptionPane.INFORMATION_MESSAGE);

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa", "root", "");

            PreparedStatement st = conectar.prepareStatement("DELETE FROM funcionarios WHERE nome = ?");
            st.setString(1, nomeFuncionario);
            int resultado = st.executeUpdate();

            if (resultado == 1) {
                JOptionPane.showMessageDialog(null, "Funcionário excluído com sucesso", "Excluir Funcionário", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Funcionário não encontrado", "Excluir Funcionário", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());

        }


    }//GEN-LAST:event_itmExcluirFuncionarioActionPerformed

    private void itmBuscarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarDepartamentosActionPerformed
        String nomeDepart;

        nomeDepart = JOptionPane.showInputDialog(null, "Digite o nome do Departamento", "Buscar Departamento", JOptionPane.INFORMATION_MESSAGE);

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa", "root", "");

            PreparedStatement st = conectar.prepareStatement("SELECT * FROM departamento WHERE nome = ?");
            st.setString(1, nomeDepart);
            ResultSet departamento = st.executeQuery();

            if (departamento.next()) {
                String id, nome, telefone;

                id = departamento.getString("id");
                nome = departamento.getString("nome");
                telefone = departamento.getString("telefone");

                JOptionPane.showMessageDialog(null,
                        "ID: " + id + "\n"
                        + "Nome: " + nome + "\n"
                        + "Telefone: " + telefone);

            } else {
                JOptionPane.showMessageDialog(null, "Departamento não encontrado");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }


    }//GEN-LAST:event_itmBuscarDepartamentosActionPerformed

    private void itmAlterarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarDepartamentosActionPerformed
        String nome;
        
        nome = JOptionPane.showInputDialog(null, "Digite o nome do Departamento:");
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conectar = DriverManager.getConnection("jdbc:mysql://localhost:3306/empresa", "root", "");
        
            PreparedStatement st = conectar.prepareStatement("SELECT * FROM departamento WHERE nome = ?");
            st.setString(1, nome);
            ResultSet departamento = st.executeQuery();
            
            if(departamento.next()){
                String id, nomeDepart, telefone;
                
                id = departamento.getString("id");
                nomeDepart = departamento.getString("nome");
                telefone = departamento.getString("telefone");
                
                new AlterarDepartamento(id, nomeDepart, telefone).setVisible(true);
            
            } else {
                JOptionPane.showMessageDialog(null, "Departamento não encontrado");
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
            
        
    }//GEN-LAST:event_itmAlterarDepartamentosActionPerformed

    private void itmListarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarDepartamentosActionPerformed
       new ListarDepartamento().setVisible(true);
    }//GEN-LAST:event_itmListarDepartamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterarDepartamentos;
    private javax.swing.JMenuItem itmAlterarFuncionarios;
    private javax.swing.JCheckBoxMenuItem itmAlterarUsuarios;
    private javax.swing.JMenuItem itmBuscarDepartamentos;
    private javax.swing.JMenuItem itmBuscarFuncionarios;
    private javax.swing.JMenuItem itmBuscarUsuarios;
    private javax.swing.JMenuItem itmCadastraUsuarios;
    private javax.swing.JMenuItem itmCadastrarDepartamentos;
    private javax.swing.JMenuItem itmCadastrarFuncionario;
    private javax.swing.JMenuItem itmExcluirDepartamentos;
    private javax.swing.JMenuItem itmExcluirFuncionario;
    private javax.swing.JMenuItem itmExcluirUsuarios;
    private javax.swing.JMenuItem itmListarDepartamentos;
    private javax.swing.JMenuItem itmListarFuncionario;
    private javax.swing.JMenuItem itmListarUsuarios;
    private javax.swing.JMenuItem itmSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuDepartamentos;
    private javax.swing.JMenu mnuFuncionarios;
    private javax.swing.JMenu mnuSair;
    private javax.swing.JMenu mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
