package telas;

import dao.TesteDao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author arauj
 */
public class ListarProdutos extends javax.swing.JFrame {

    /**
     * Creates new form ListarProdutos
     */
    public ListarProdutos() {
        initComponents();
        listarProduto();
    }

    //Método privado para listar todos os usuários;
    private void listarProduto() {
        try {
            //1 - Conexão com o BD;
            ResultSet produto = new TesteDao().listarTodosOsProdutos();

            /*
            Como o Java não deixa colocar diretamente os dados dentro da tabela 
            temos que criar um "molde", onde fazemos um casting
             */
            DefaultTableModel tblModelo = (DefaultTableModel) tblProdutos.getModel();
            tblModelo.setRowCount(0); //Limpa a tabela

            //Passa linha por linha até o final da tabela;
            while (produto.next()) {
                //Vetor que adicionará os dados do BD
                String[] linha = {
                    produto.getString("id"),
                    produto.getString("nome"),
                    produto.getString("marca"),
                    produto.getString("composicao")
                };
                //Adicionando os dados na tabela
                tblModelo.addRow(linha);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        btnListaraMarcas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar os Produtos");
        getContentPane().setLayout(null);

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Marca", "Composição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblProdutos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 70, 670, 270);

        lblMarca.setText("Marca:");
        getContentPane().add(lblMarca);
        lblMarca.setBounds(20, 20, 90, 30);

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMarca);
        txtMarca.setBounds(110, 20, 430, 30);

        btnListaraMarcas.setText("Listar Marcas");
        btnListaraMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaraMarcasActionPerformed(evt);
            }
        });
        getContentPane().add(btnListaraMarcas);
        btnListaraMarcas.setBounds(575, 20, 110, 30);

        setSize(new java.awt.Dimension(726, 367));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void btnListaraMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaraMarcasActionPerformed
        String marca;

        marca = txtMarca.getText();

        try {
            //1 - Conexão com o BD;
            ResultSet produto = new TesteDao().listarProdutosPorMarca(marca);

            /*
            Como o Java não deixa colocar diretamente os dados dentro da tabela 
            temos que criar um "molde", onde fazemos um casting
             */
            DefaultTableModel tblModelo = (DefaultTableModel) tblProdutos.getModel();
            tblModelo.setRowCount(0); //Limpa a tabela

            //Passa linha por linha até o final da tabela;
            while (produto.next()) {
                //Vetor que adicionará os dados do BD
                String[] linha = {
                    produto.getString("id"),
                    produto.getString("nome"),
                    produto.getString("marca"),
                    produto.getString("composicao")
                };
                //Adicionando os dados na tabela
                tblModelo.addRow(linha);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnListaraMarcasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListaraMarcas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtMarca;
    // End of variables declaration//GEN-END:variables
}
