package telas;

import dao.TesteDao;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author arauj
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuProduto = new javax.swing.JMenu();
        itmCadastrarProduto = new javax.swing.JMenuItem();
        itmAlterarProduto = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itmBuscarProduto = new javax.swing.JMenuItem();
        itmExcluirProduto = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itmListarProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telas/baixados.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -480, 860, 910);

        mnuProduto.setMnemonic('p');
        mnuProduto.setText("Produto");

        itmCadastrarProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCadastrarProduto.setText("Cadastrar");
        itmCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarProdutoActionPerformed(evt);
            }
        });
        mnuProduto.add(itmCadastrarProduto);

        itmAlterarProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmAlterarProduto.setText("Alterar");
        itmAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarProdutoActionPerformed(evt);
            }
        });
        mnuProduto.add(itmAlterarProduto);
        mnuProduto.add(jSeparator1);

        itmBuscarProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmBuscarProduto.setText("Buscar");
        itmBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBuscarProdutoActionPerformed(evt);
            }
        });
        mnuProduto.add(itmBuscarProduto);

        itmExcluirProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmExcluirProduto.setText("Excluir");
        itmExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirProdutoActionPerformed(evt);
            }
        });
        mnuProduto.add(itmExcluirProduto);
        mnuProduto.add(jSeparator2);

        itmListarProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmListarProduto.setText("Listar");
        itmListarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarProdutoActionPerformed(evt);
            }
        });
        mnuProduto.add(itmListarProduto);

        jMenuBar1.add(mnuProduto);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(748, 398));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarProdutoActionPerformed
        new CadastrarProduto().setVisible(true);
    }//GEN-LAST:event_itmCadastrarProdutoActionPerformed

    private void itmExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirProdutoActionPerformed
        // Pegar o id do produto;
        String idProduto;

        idProduto = JOptionPane.showInputDialog(null, "Digite o código do produto para excluí-lo", "Excluir produto", JOptionPane.INFORMATION_MESSAGE);

        if (idProduto == null) {
            return;
        }

        try {
            int retorno = new TesteDao().excluirProduto(idProduto);

            if (retorno == 1) { // Se o retorno da variável int "retorno" for 1, ou seja se o produto for encontrado; 
                JOptionPane.showMessageDialog(null, "Produto excluido com sucesso", "Produto Excluido", JOptionPane.INFORMATION_MESSAGE);

            } else { // Se não encontrar o produto
                JOptionPane.showMessageDialog(null, "Produto não encontrado", "Mensagem", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());

        }
    }//GEN-LAST:event_itmExcluirProdutoActionPerformed

    private void itmBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBuscarProdutoActionPerformed
        //0 - Variável para buscar o produto pelo nome;
        String nome;

        nome = JOptionPane.showInputDialog(null, "Produto a buscar", "Buscar Produto", JOptionPane.INFORMATION_MESSAGE);

        if (nome == null) {
            return;
        }

        try {
            ResultSet produto = new TesteDao().buscarProdutos(nome);

            if (produto.next()) { //Verifica se o produto foi encontrado
                String id, name, marca, composicao;

                //As variáveis criadas acima vão pegar os dados de cada coluna do BD;
                id = produto.getString("id");
                name = produto.getString("nome");
                marca = produto.getString("marca");
                composicao = produto.getString("composicao");

                // Imprimi na tela os valores que as variáveis puxaram do BD puxou;
                JOptionPane.showMessageDialog(null,
                        "ID do Produto: " + id + "\n"
                        + "Nome: " + name + "\n"
                        + "Marca: " + marca + "\n"
                        + "Composição: " + composicao
                );

            } else { // Se o produto não for encotrado retorna essa mensagem de erro
                JOptionPane.showMessageDialog(null, "Produto não encontrado", "Produto", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }
    }//GEN-LAST:event_itmBuscarProdutoActionPerformed

    private void itmListarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarProdutoActionPerformed
        new ListarProdutos().setVisible(true);
    }//GEN-LAST:event_itmListarProdutoActionPerformed

    private void itmAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarProdutoActionPerformed
        //0 - Variáveis que pega o nome do produto
        String nome;

        nome = JOptionPane.showInputDialog(null, "Produto a alterar", "Alterar o Produto", JOptionPane.INFORMATION_MESSAGE);

        if (nome == null) {
            return;
        }

        try {
            ResultSet produto = new TesteDao().buscarProdutos(nome);

            if (produto.next()) { //Se encontrar o produto
                String id, name, marca, composicao;

                //Adiciona as variáveis criadas acima e adiciona com cada atributo(coluna) no BD;
                id = produto.getString("id");
                name = produto.getString("nome");
                marca = produto.getString("marca");
                composicao = produto.getString("composicao");

                //Liga a tela/classe para alterar os produtos;
                new AlterarProdutos(id, name, marca, composicao).setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Produto não encontrado", "Produto", JOptionPane.WARNING_MESSAGE);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Entre em contato com o suporte e informe o erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_itmAlterarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterarProduto;
    private javax.swing.JMenuItem itmBuscarProduto;
    private javax.swing.JMenuItem itmCadastrarProduto;
    private javax.swing.JMenuItem itmExcluirProduto;
    private javax.swing.JMenuItem itmListarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnuProduto;
    // End of variables declaration//GEN-END:variables
}
